### ISSUE TITLE
Arduino compile error.

### ISSUE THREAD

**Issue by vortex469** [CuriousTech/ESP8266-HVAC#1]
Tried to compile with arduino 1.6.8 and i get the following error.

sketch\HVAC.cpp: In member function 'void HVAC::tempCheck()':

sketch\HVAC.cpp:270:15: error: 'second' was not declared in this scope

```
 if(second() == 0 || m_bRecheck) // readjust while running

           ^
```

sketch\HVAC.cpp:293:15: error: 'second' was not declared in this scope

```
 if(second() == 0 || m_bRecheck)

           ^
```

exit status 1

**Comment by CuriousTech** [comment]
@vortex469 This appears to be a problem with IDE versions after 1.6.5.  I'm not sure how to fix it other than renaming the Time library or building with 1.6.5.

**Comment by CuriousTech** [comment]
Updated code.  The Time library already had this fix by using TimeLib.h
